[package]
name = "ink"
version = "0.1.6"
edition = "2024"
authors = ["pero-sk"]
description = "A small, terminal-based text editor"
repository = "https://github.com/pero-sk/ink"
homepage = "https://github.com/pero-sk/ink"
readme = "README.md"
license = "Apache 2.0"
keywords = ["editor", "text-editor", "terminal", "tui", "small"]
categories = ["text-editors"]

[[bin]]
name = "ink"
path = "src/main.rs"

[dependencies]
crossterm = "0.27"
unicode-width = "0.1"
unicode-segmentation = "1.11"
arboard = { version = "3.4", features = ["wayland-data-control"] }
clap = { version = "4.6.6", features = ["derive"] }
rhai = "1.25.1"
dirs = "6.0.0"

[profile.release]
opt-level = 3
lto = true

[package.metadata.deb]
maintainer = "Beata C <beata.c@kittymail.com>"
copyright = "2026, pero-sk"
license-file = ["LICENSE", "0"]
section = "editors"
priority = "optional"
depends = ["libc6", "libgcc-s1"]
extended-description = """\
Ink is a small, terminal-based text editor written in Rust.

It is designed to be lightweight and keyboard-driven, with a simple command
language and a small codebase.
"""
assets = [
    ["target/release/ink", "usr/bin/", "755"],
    ["ink.1", "usr/share/man/man1/", "644"],
    ["LICENSE", "usr/share/doc/ink/", "644"],
]
